name: food_delivery_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.0.1
  provider: ^6.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/Burger/
    - lib/images/Desserts/
    - lib/images/Drinks/
    - lib/images/Salads/
    - lib/images/Sides/
    - lib/images/icons/chip.png
